FROM amd64/debian:buster

RUN apt-get update && apt-get install -y --no-install-recommends \
    python3 \
    python3-pip \
    libproj13 \
    ca-certificates \
&& rm -rf /var/lib/apt/lists/*

RUN pip3 install wheel setuptools && \
    pip3 install Pillow PyYAML MapProxy

COPY entrypoint.sh /usr/local/bin
RUN chmod +x /usr/local/bin/entrypoint.sh

#VOLUME
EXPOSE 80

ENTRYPOINT ["entrypoint.sh"]
CMD ["mapproxy-util", "serve-develop", "/mymapproxy/mapproxy.yaml", "--bind", "0.0.0.0:80"]
