FROM i386/debian:buster

RUN apt-get update && apt-get install -y --no-install-recommends \
    python3 \
    python3-pip \
    libproj13 \
    ca-certificates \
&& rm -rf /var/lib/apt/lists/*

RUN pip3 install wheel setuptools && \
    pip3 install Pillow PyYAML MapProxy && \
    mkdir -p /mapproxy_conf /mapproxy_cache /mapproxy_locks/locks /mapproxy_locks/tile_locks

COPY entrypoint.sh /usr/local/bin
RUN chmod +x /usr/local/bin/entrypoint.sh

VOLUME /mapproxy_conf /mapproxy_cache
EXPOSE 80

ENTRYPOINT ["entrypoint.sh"]
CMD ["mapproxy-util", "serve-develop", "/mapproxy_conf/custom.yaml", "--bind", "0.0.0.0:80"]