FROM mattiasegly/base-image:buster-386

RUN apt-get update && apt-get install -y --no-install-recommends \
    python3 \
    python3-pip \
    python3-setuptools \
    python3-wheel \
    python3-pil \
    python3-yaml \
    python3-pyproj \
&& rm -rf /var/lib/apt/lists/* \
&& update-alternatives --install /usr/bin/python python /usr/bin/python3 1 \
&& update-alternatives --install /usr/bin/pip pip /usr/bin/pip3 1

RUN pip install MapProxy waitress && \
    mkdir -p /mapproxy_conf /mapproxy_cache /mapproxy_locks/locks /mapproxy_locks/tile_locks

COPY entrypoint.sh /usr/local/bin
RUN chmod +x /usr/local/bin/entrypoint.sh

VOLUME /mapproxy_conf /mapproxy_cache
EXPOSE 80

WORKDIR /mapproxy_conf
ENTRYPOINT ["entrypoint.sh"]
CMD ["waitress-serve", "--port=80", "config:application"]
#CMD ["mapproxy-util", "serve-develop", "/mapproxy_conf/custom.yaml", "--bind", "0.0.0.0:80"]
